### ISSUE TITLE
Usage of ARtoolkit instead of ARkit

### ISSUE THREAD

**Issue by msmshazan** [BastiaanOlij/godot_openvr#10]
Usage of ARtoolkit (https://artoolkit.org) instead of apple's arkit since the former is open source

**Comment by BastiaanOlij** [comment]
This probably should be an issue on the main godot repository, this repository is for OpenVR development.

That said, it would be interesting to look into implementing this as an ARVR plugin. I've started work on enhancing the Camera Feed logic that is still in development to be extendable through GDNative. That would allow the camera feed from a GDNative implemented AR solution to provide a background image.

Not knowing anything about the internals of the ARToolkit, in theory the rest should be possible as a GDNative module. Only downside is the same as with ARKit, apple does not allow deployment of dynamic libraries on iOS.

**Comment by msmshazan** [comment]
If you're curious about the license ```
ARToolKit versions 5.2 and later are made available freely under the GNU Library General Public License version 3 (LGPLv3), with the addition of a special exception permitting static linking.```

**Comment by msmshazan** [comment]
Okay then I'll probably move it the issue to the main Godot repo

**Comment by BastiaanOlij** [comment]
The problem of static linking lies more on the Godot side of life. One of the things we're trying to minimise is bloating the core of Godot with a lot of logic people won't be using.

Dynamic libraries such as the OpenVR plugin make it so that only developers who actually want to publish a VR game will include the code.

As ARKit is part of the OS the additions to Godot are minor but ARToolkit is a complete full featured package which would result in a relatively huge increase of the Godot executable size while most developers won't be developing for AR.

So the preference would be to develop an ARToolkit GDNative plugin but that would be hard to deploy. Endragor and Karroffel were discussing options the other day on how we could make it optional to statically link a GDNative plugin when required.

**Comment by BastiaanOlij** [comment]
Closed as discussion moved to main godot repo
